#! /bin/sh

sxhkd &


bspc monitor DVI-D-0 -d I II III IV 
bspc monitor HDMI-A-3 -d V VI VII
bspc monitor HDMI-A-4 -d VIII IX X


bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#fixes ugly x cursor
xsetroot -cursor_name left_ptr


#startup programs
bspc wm -O DVI-D-0 HDMI-A-3 HDMI-A-4 &
~/.config/polybar/launch.sh &
picom -b &
xset r rate 150 35 &
xrandr --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-3 --mode 1920x1080 --pos 3280x0 --rotate normal --output HDMI-A-4 --mode 1360x768 --pos 0x0 --rotate normal --output DVI-D-0 --primary --mode 1920x1080 --rate 144 --pos 1360x0 --rotate normal --output HDMI-1-1 --off --output HDMI-1-2 --off --output DP-1-1 --off --output HDMI-1-3 --off

feh --bg-max ~/Pictures/Wallpapers/cp2.jpg --bg-fill ~/Pictures/Wallpapers/cp3.jpg --bg-fill ~/Pictures/Wallpapers/cp4.png &
dropbox &
ntpd -qg &
dunst &
mpd &
ranger &


